-- Auto-generated by Mechanic Desktop CLI
-- This file is read by Mechanic on addon load
-- Do not edit manually

MECHANIC_LUA_QUEUE = {
	{
		["label"] = "snippet_1",
		["code"] = [[return 1 + 1]],
	}
}
