-- Auto-generated by Mechanic Desktop CLI
-- This file is read by Mechanic on addon load
-- Do not edit manually

MECHANIC_LUA_QUEUE = {
	{
		["label"] = "BuffBarCooldownViewer structure",
		["code"] = [[local blizzFrame = BuffBarCooldownViewer; if not blizzFrame then return 'BuffBarCooldownViewer not found' end; local result = {}; if blizzFrame.itemFramePool then for itemFrame in blizzFrame.itemFramePool:EnumerateActive() do local info = {name = itemFrame:GetName() or 'unnamed'}; info.children = {}; for i, child in ipairs({itemFrame:GetChildren()}) do local childInfo = {name = child:GetName() or child:GetObjectType()}; if child == itemFrame.Icon then childInfo.isIcon = true end; if child == itemFrame.Bar then childInfo.isBar = true end; if child.Cooldown then childInfo.hasCooldown = true end; if child.cooldown then childInfo.hasLowerCooldown = true end; table.insert(info.children, childInfo) end; if itemFrame.Icon then info.iconChildren = {}; for i, c in ipairs({itemFrame.Icon:GetChildren()}) do table.insert(info.iconChildren, c:GetName() or c:GetObjectType()) end end; if itemFrame.Bar then info.barType = itemFrame.Bar:GetObjectType() end; table.insert(result, info); break end end; return result]],
	}
}
