"""
Asset management commands for WoW addon development.
Handles PNG to TGA conversion and asset synchronization.

Migrated from ADDON_DEV/Tools/AssetManager to AFD commands.
"""

import asyncio
import json
import shutil
from pathlib import Path
from typing import Any, Dict, List, Set

from afd import CommandResult, error, success
from pydantic import BaseModel, Field

from ..config import find_addon_path
from ._common import addon_not_found

MANIFEST_NAME = ".mechanic-assets.json"


# ═══════════════════════════════════════════════════════════════════════════════
# SCHEMAS
# ═══════════════════════════════════════════════════════════════════════════════


class AssetsSyncInput(BaseModel):
    addon: str = Field(..., description="Name of the addon to sync assets for")
    dry_run: bool = Field(
        default=False,
        description="Report what would be converted, copied and removed without changing files",
    )


class AssetsSyncOutput(BaseModel):
    addon: str
    dry_run: bool = False
    converted: int = Field(..., description="Number of PNG files converted to TGA")
    copied: int = Field(..., description="Number of files directly copied")
    removed: int = Field(
        ..., description="Number of previously generated files removed (source deleted)"
    )
    removed_files: List[str] = Field(
        default_factory=list, description="Generated files removed or to be removed"
    )
    warnings: List[str] = Field(default_factory=list, description="Validation warnings")


class AssetsListInput(BaseModel):
    addon: str = Field(..., description="Name of the addon")


class AssetsListOutput(BaseModel):
    addon: str
    source_count: int
    target_count: int
    source_files: List[str]
    target_files: List[str]


# ═══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════


def _check_pillow_available() -> bool:
    """Check if Pillow is installed."""
    try:
        from PIL import Image

        _ = Image
        return True
    except ImportError:
        return False


def _is_power_of_two(n: int) -> bool:
    """Check if a number is a power of 2."""
    return (n & (n - 1) == 0) and n != 0


def _validate_dimensions(width: int, height: int) -> List[str]:
    """Validate image dimensions for WoW compatibility."""
    issues = []
    if not _is_power_of_two(width):
        issues.append(f"Width ({width}) is not a power of 2")
    if not _is_power_of_two(height):
        issues.append(f"Height ({height}) is not a power of 2")
    return issues


def _load_manifest(target_dir: Path) -> Set[str]:
    """Files a previous sync generated (relative posix paths)."""
    try:
        data = json.loads((target_dir / MANIFEST_NAME).read_text(encoding="utf-8"))
        return {str(p) for p in data.get("generated", [])}
    except (OSError, ValueError, AttributeError, TypeError):
        return set()


def _save_manifest(target_dir: Path, generated: Set[str]) -> None:
    (target_dir / MANIFEST_NAME).write_text(
        json.dumps({"generated": sorted(generated)}, indent=2) + "\n", encoding="utf-8"
    )


def _sync_assets(addon_path: Path, dry_run: bool = False) -> Dict[str, Any]:
    """
    Sync assets from assets_source to assets folder.
    Converts PNG to TGA and copies other files directly. Only files recorded in
    the manifest as generated by an earlier sync are ever removed, so hand-made
    files in ``assets/`` are never deleted.
    """
    from PIL import Image

    source_dir = addon_path / "assets_source"
    target_dir = addon_path / "assets"

    result: Dict[str, Any] = {
        "converted": 0,
        "copied": 0,
        "removed": 0,
        "removed_files": [],
        "warnings": [],
    }

    if not source_dir.exists():
        return result

    previous = _load_manifest(target_dir)
    generated: Set[str] = set()

    for source_file in sorted(source_dir.rglob("*")):
        if source_file.is_dir():
            continue

        rel_path = source_file.relative_to(source_dir)
        is_png = source_file.suffix.lower() == ".png"
        target_rel = rel_path.with_suffix(".tga") if is_png else rel_path
        target_file = target_dir / target_rel
        key = target_rel.as_posix()
        if key == MANIFEST_NAME:
            continue

        up_to_date = (
            target_file.exists()
            and source_file.stat().st_mtime <= target_file.stat().st_mtime
        )
        if up_to_date:
            if key in previous:
                generated.add(key)
            continue

        if not is_png:
            generated.add(key)
            if dry_run:
                result["copied"] += 1
                continue
            try:
                target_file.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source_file, target_file)
                result["copied"] += 1
            except Exception as e:
                generated.discard(key)
                result["warnings"].append(f"Error copying {source_file.name}: {e}")
            continue

        try:
            with Image.open(source_file) as img:
                issues = _validate_dimensions(*img.size)
                if issues:
                    result["warnings"].append(
                        f"{source_file.name}: {', '.join(issues)}"
                    )
                if not dry_run:
                    target_file.parent.mkdir(parents=True, exist_ok=True)
                    # 32-bit TGA needs RGBA
                    (img if img.mode == "RGBA" else img.convert("RGBA")).save(
                        target_file, "TGA"
                    )
            generated.add(key)
            result["converted"] += 1
        except Exception as e:
            result["warnings"].append(f"Error converting {source_file.name}: {e}")

    # Remove only files an earlier sync generated whose source is now gone
    for key in sorted(previous - generated):
        stale = target_dir / key
        still_wanted = (source_dir / key).exists() or (
            key.lower().endswith(".tga")
            and (source_dir / Path(key).with_suffix(".png")).exists()
        )
        if (
            still_wanted
            or not stale.is_file()
            or not stale.resolve().is_relative_to(target_dir.resolve())
        ):
            continue
        result["removed_files"].append(key)
        result["removed"] += 1
        if dry_run:
            continue
        try:
            stale.unlink()
        except OSError as e:
            result["removed"] -= 1
            result["removed_files"].remove(key)
            result["warnings"].append(f"Could not remove {key}: {e}")
            generated.add(key)
            continue
        # Drop folders the removal emptied
        for parent in stale.parents:
            if parent == target_dir or not parent.is_relative_to(target_dir):
                break
            try:
                parent.rmdir()
            except OSError:
                break

    if not dry_run and (generated or previous):
        target_dir.mkdir(parents=True, exist_ok=True)
        _save_manifest(target_dir, generated)

    return result


# ═══════════════════════════════════════════════════════════════════════════════
# COMMAND IMPLEMENTATIONS
# ═══════════════════════════════════════════════════════════════════════════════


async def _assets_sync(
    input: AssetsSyncInput, context: Any = None
) -> CommandResult[AssetsSyncOutput]:
    """
    Sync assets from assets_source to assets folder.
    Converts PNG files to TGA format for WoW compatibility.
    """
    if not _check_pillow_available():
        return error(
            code="PACKAGE_MISSING",
            message="Pillow package not installed",
            suggestion="Install with: pip install Pillow  OR  pip install mechanic-desktop[assets]",
        )

    addon_path = find_addon_path(input.addon)
    if not addon_path:
        return addon_not_found(
            input.addon, "Check the addon name and ensure it exists in the dev path."
        )

    source_dir = addon_path / "assets_source"
    if not source_dir.exists():
        return error(
            code="NO_ASSETS_SOURCE",
            message=f"No assets_source directory found in {input.addon}",
            suggestion="Create an 'assets_source' folder with PNG files to convert.",
        )

    try:
        result = await asyncio.to_thread(_sync_assets, addon_path, input.dry_run)
    except Exception as e:
        return error(
            code="SYNC_FAILED",
            message=f"Asset sync failed: {e}",
            suggestion="Check file permissions and ensure assets_source contains valid files.",
        )

    verb = "Would sync" if input.dry_run else "Synced assets"
    return success(
        data=AssetsSyncOutput(
            addon=input.addon,
            dry_run=input.dry_run,
            converted=result["converted"],
            copied=result["copied"],
            removed=result["removed"],
            removed_files=result["removed_files"],
            warnings=result["warnings"],
        ),
        reasoning=f"{verb}: {result['converted']} converted, {result['copied']} copied, {result['removed']} removed",
    )


async def _assets_list(
    input: AssetsListInput, context: Any = None
) -> CommandResult[AssetsListOutput]:
    """
    List asset files in an addon's assets_source and assets folders.
    """
    addon_path = find_addon_path(input.addon)
    if not addon_path:
        return addon_not_found(
            input.addon, "Check the addon name and ensure it exists in the dev path."
        )

    def list_files(folder: Path) -> List[str]:
        if not folder.exists():
            return []
        return sorted(
            f.relative_to(folder).as_posix()
            for f in folder.rglob("*")
            if f.is_file() and f.name != MANIFEST_NAME
        )

    source_files = await asyncio.to_thread(list_files, addon_path / "assets_source")
    target_files = await asyncio.to_thread(list_files, addon_path / "assets")

    return success(
        data=AssetsListOutput(
            addon=input.addon,
            source_count=len(source_files),
            target_count=len(target_files),
            source_files=source_files[:50],  # Limit output
            target_files=target_files[:50],
        ),
        reasoning=f"Found {len(source_files)} source files and {len(target_files)} target files",
    )


# ═══════════════════════════════════════════════════════════════════════════════
# REGISTRATION
# ═══════════════════════════════════════════════════════════════════════════════


def register_commands(server):
    """Register asset management commands with the AFD server."""

    server.command(
        name="assets.sync",
        description="Sync addon assets: convert PNG to TGA and copy other files from assets_source to assets; removes only files a previous sync generated; supports dry_run",
        input_schema=AssetsSyncInput,
        output_schema=AssetsSyncOutput,
    )(_assets_sync)

    server.command(
        name="assets.list",
        description="List asset files in an addon's assets_source and assets folders",
        input_schema=AssetsListInput,
        output_schema=AssetsListOutput,
    )(_assets_list)
