"""
Lua Eval Queue Commands for Mechanic Desktop.

Provides round-trip Lua execution:
- lua.queue: Queue Lua code for in-game execution
- lua.results: Read results from last eval (via addon.output)

Workflow:
1. Agent calls `lua.queue` with code snippets
2. User does /reload in WoW
3. Addon executes code and stores results
4. Agent reads results via `addon.output` or `lua.results`
"""

from pathlib import Path
from typing import Any, Dict, List, Optional

from afd import CommandResult, success, error
from afd.core.metadata import create_source
from pydantic import BaseModel, Field

from ..targets import (
    DiagnosticTarget,
    SelectedTarget,
    TargetError,
    select_target,
    read_profile,
    queue_target_lua,
)

from ..lua_strings import quote_lua_string as escape_lua_label


# ═══════════════════════════════════════════════════════════════════════════════
# SCHEMAS
# ═══════════════════════════════════════════════════════════════════════════════


class LuaQueueInput(BaseModel):
    target: Optional[DiagnosticTarget] = None
    code: List[str] = Field(
        ...,
        description="List of Lua code snippets to execute. Each snippet should return a value.",
    )
    labels: Optional[List[str]] = Field(
        None,
        description="Optional labels for each snippet (for easier identification in results)",
    )


class LuaQueueResult(BaseModel):
    target: Optional[SelectedTarget] = None
    queued: int
    queue_file: str
    snippets: List[str]
    message: str


class LuaResultsInput(BaseModel):
    target: Optional[DiagnosticTarget] = None
    pass  # No input needed


class LuaResultsResult(BaseModel):
    target: Optional[SelectedTarget] = None
    results: List[Dict[str, Any]]
    total: int
    last_run: Optional[str]


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════


def find_addon_path() -> Optional[Path]:
    from ..targets import discover_targets

    candidates = [c for c in discover_targets() if Path(c.addon_path).exists()]
    return Path(select_target(candidates=candidates).addon_path) if candidates else None


def escape_lua_string(s: str) -> str:
    """Escape a string for Lua long string format."""
    # Use Lua long string format [[ ]] which doesn't need escaping
    # But we need to handle nested brackets
    level = 0
    while f"]{('=' * level)}]" in s or f"[{('=' * level)}[" in s:
        level += 1
    return f"[{'=' * level}[{s}]{'=' * level}]"


def write_lua_queue_file(
    snippets: List[str],
    labels: Optional[List[str]] = None,
    target: Optional[SelectedTarget] = None,
) -> Optional[Path]:
    """
    Write the Lua eval queue to MechanicQueue.lua.

    Completely rewrites the file (both API and Lua queues are written fresh).
    """
    addon_path = Path(target.addon_path) if target else find_addon_path()
    if not addon_path or not addon_path.exists():
        return None

    queue_file = addon_path / "MechanicQueue.lua"

    # Build the Lua table for the queue
    queue_items = []
    for i, code in enumerate(snippets):
        label = labels[i] if labels and i < len(labels) else f"snippet_{i + 1}"
        escaped_code = escape_lua_string(code)
        escaped_label = escape_lua_label(label)
        queue_items.append(
            f'\t{{\n\t\t["label"] = {escaped_label},\n'
            f'\t\t["code"] = {escaped_code},\n\t}}'
        )

    queue_lua = "{\n" + ",\n".join(queue_items) + "\n}"

    # Always write fresh - don't try to preserve old content
    content = f"""-- Auto-generated by Mechanic Desktop CLI
-- This file is read by Mechanic on addon load
-- Do not edit manually

MECHANIC_LUA_QUEUE = {queue_lua}
"""

    if target:
        content = queue_target_lua(target) + content
    queue_file.write_text(content, encoding="utf-8")
    return queue_file


def get_lua_results(target=None) -> Dict[str, Any]:
    return read_profile(target or select_target()).get("luaEvalResults", {})


# ═══════════════════════════════════════════════════════════════════════════════
# COMMANDS
# ═══════════════════════════════════════════════════════════════════════════════


def register_commands(server):
    """Register Lua eval commands with the server."""

    @server.command(
        name="lua.queue",
        description="Queue Lua code snippets for in-game execution. After running this, /reload in WoW to execute.",
        input_schema=LuaQueueInput,
        output_schema=LuaQueueResult,
    )
    async def lua_queue(
        input: LuaQueueInput, context: Any = None
    ) -> CommandResult[LuaQueueResult]:
        if not input.code:
            return error(
                code="NO_CODE",
                message="No code snippets provided",
                suggestion="Provide at least one Lua code snippet",
            )

        # Validate labels count matches if provided
        if input.labels and len(input.labels) != len(input.code):
            return error(
                code="LABEL_MISMATCH",
                message=f"Labels count ({len(input.labels)}) doesn't match code count ({len(input.code)})",
                suggestion="Provide one label per code snippet, or omit labels",
            )

        # Write to queue file
        try:
            selected = select_target(input.target)
            queue_path = write_lua_queue_file(input.code, input.labels, selected)
        except TargetError as exc:
            return exc.result()

        if not queue_path:
            return error(
                code="ADDON_NOT_FOUND",
                message="Could not find !Mechanic addon folder",
                suggestion="Ensure !Mechanic is installed in Interface/AddOns",
            )

        # Generate preview of snippets
        previews = []
        for i, code in enumerate(input.code):
            label = input.labels[i] if input.labels else f"snippet_{i + 1}"
            preview = code[:50] + "..." if len(code) > 50 else code
            previews.append(f"{label}: {preview}")

        return success(
            data=LuaQueueResult(
                target=selected,
                queued=len(input.code),
                queue_file=str(queue_path),
                snippets=previews,
                message=f"Queued {len(input.code)} Lua snippet(s). /reload in WoW to execute.",
            ),
            reasoning=f"Wrote {len(input.code)} Lua snippets to {queue_path.name}",
        )

    @server.command(
        name="lua.results",
        description="Get results from the last Lua eval queue execution",
        input_schema=LuaResultsInput,
        output_schema=LuaResultsResult,
    )
    async def lua_results(
        input: LuaResultsInput, context: Any = None
    ) -> CommandResult[LuaResultsResult]:
        try:
            selected = select_target(input.target)
            results_data = get_lua_results(selected)
        except TargetError as exc:
            return exc.result()

        if not results_data:
            return success(
                data=LuaResultsResult(
                    target=selected, results=[], total=0, last_run=None
                ),
                reasoning="No Lua eval results found. Queue some code with lua.queue, then /reload in WoW.",
            )

        results = results_data.get("results", [])
        last_run = results_data.get("lastRun")

        src = create_source(
            type="file", id="mechanic-db", title="MechanicDB Lua Results"
        )

        return success(
            data=LuaResultsResult(
                target=selected,
                results=results
                if isinstance(results, list)
                else list(results.values()),
                total=len(results) if isinstance(results, (list, dict)) else 0,
                last_run=last_run,
            ),
            reasoning=f"Found {len(results)} Lua eval results from {last_run or 'unknown time'}",
            sources=[src],
        )
